### ISSUE TITLE
level loading

### ISSUE THREAD

**Issue by MoserLukas2004** [MoserLukas2004/geometry-dash-clone#4]
how to define/create a level
how to load a level

**Comment by Noah2610** [comment]
@MoserLukas2004 
Now that we have a web server running with `http-server`, we could load the level from a text or JSON file instead of storing it as a string in a JS file.
This way, we could store many level files. In the future we could maybe select a level from the game.

https://p5js.org/reference/#/p5/loadStrings
https://p5js.org/reference/#/p5/loadJSON
